trigger:
  branches:
    include:
      - master

variables:
  imageName: 'myapp'
  acrName: 'myacr.azurecr.io'
  tag: '$(Build.BuildId)'

stages:

# =========================
# SONARQUBE
# =========================
- stage: SonarQube
  displayName: "Code Analysis"
  jobs:
    - job: SonarAnalysis
      pool:
        name: 'Default'

      steps:
        - checkout: self

        - script: |
            cd Amazon
            mvn clean verify sonar:sonar \
              -Dsonar.projectKey=my-app \
              -Dsonar.host.url=http://4.155.39.53:9000 \
              -Dsonar.login=sqa_9d6b3f1d8d52f545d3c3d6d46a7674709f08d955
          displayName: "Run SonarQube Scan"

# =========================
# 3: MAVEN BUILD + ARTIFACT
# =========================
- stage: Build
  displayName: "Build & Artifact"
  dependsOn: SonarQube
  jobs:
    - job: MavenBuild
      pool:
        name: 'Default'

      steps:
        - checkout: self

        - task: Maven@3
          inputs:
            mavenPomFile: 'Amazon/pom.xml'
            goals: 'clean package'
            publishJUnitResults: true

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'Amazon/Amazon-Web/target'
            artifactName: 'drop'

# =========================
# 4: DOCKER BUILD
# =========================


- stage: DockerBuild
  displayName: "Build Docker Image"
  dependsOn: Build

  jobs:
    - job: DockerBuildJob
      pool:
        name: 'Default'

      steps:
        - checkout: self

        - task: Docker@2
          inputs:
            containerRegistry: 'ACR'
            repository: '$(imageName)'
            command: 'build'
            Dockerfile: 'Amazon/Dockerfile'
            buildContext: '$(Build.SourcesDirectory)/Amazon'
            tags: |
              $(tag)

        - script: |
            echo "==== DOCKER IMAGES ===="
            docker images
          displayName: "Check Images"

        - script: |
            echo "==== FINDING IMAGE ===="
            docker images

            IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep myapp | head -n 1)

            echo "Found image: $IMAGE"

            docker save $IMAGE -o image.tar
          displayName: "Save Docker Image (Dynamic)"

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'image.tar'
            artifactName: 'docker-image'

# =========================
# 5: PUSH TO ACR
# =========================
- stage: Push
  displayName: "Push to ACR"
  dependsOn: DockerBuild

  jobs:
    - job: PushJob
      pool:
        name: 'Default'

      steps:
        - download: current
          artifact: docker-image

        - script: |
            echo "Loading image..."
            docker load -i $(Pipeline.Workspace)/docker-image/image.tar

            echo "==== DOCKER IMAGES AFTER LOAD ===="
            docker images

            IMAGE=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep myapp | head -n 1)
            echo "Found image: $IMAGE"

            docker tag $IMAGE $(acrName)/$(imageName):$(tag)

            echo "==== AFTER TAGGING ===="
            docker images
          displayName: "Load + Tag Image"

        - task: Docker@2
          displayName: "Push to ACR"
          inputs:
            containerRegistry: 'ACR'
            repository: '$(imageName)'
            command: 'push'
            tags: |
              $(tag)

# =========================
# 6: TRIVY SCAN
# =========================
- stage: SecurityScan
  displayName: "Trivy Scan"
  dependsOn: Push
  jobs:
    - job: TrivyScan
      pool:
        name: 'Default'
        
      
      steps:
        - script: |
            trivy image --exit-code 0 --severity HIGH,CRITICAL $(acrName)/$(imageName):$(tag)
          displayName: "Scan Docker Image"

# =========================
# 7: DEPLOY TO AKS
# =========================
- stage: Deploy
  displayName: "Deploy to AKS"
  dependsOn: SecurityScan
  jobs:
    - job: DeployJob
      pool:
        name: 'Default'
        
      steps:
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'AKS'
            namespace: default
            command: apply
            useConfigurationFile: true
            configuration: 'k8s/deployment.yaml'