pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'master', url: 'https://github.com/Rohan0322/Amazon_Maven.git'
            }
        }

        stage('Validate') {
            steps {
                dir('Amazon') {
                    sh 'ls -l'
                    sh 'mvn validate'
                }
            }
        }

        stage('Compileee') {
            steps {
                dir('Amazon') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Amazon') {
                    sh 'mvn test'
                }
            }
        }

        stage('Buildd') {
            steps {
                dir('Amazon') {
                    sh 'mvn package'
                }
            }
        }
    }
}
